// Project inventory from Company Profile 2026 Q2. Every entry is `unreviewed`:
// client attribution and publication need confirmation before launch (see docs/content-todo.md).
// Photography/video are not included: none has been approved for public use.

export type Region3 = "uae" | "ksa" | "international";

export interface Project {
  slug: string;
  title: string;
  /** Client / agency relationship exactly as stated in the profile. Empty = not stated; confirm before launch. */
  client: string;
  event: string;
  location: string;
  region: Region3;
  year: number;
  sector: string;
  summary: string;
  technologies: string[];
  caseStudy?: boolean;
  /** CMS-only fields (absent for the built-in starter content). */
  clientAttribution?: string;
  challenge?: string;
  experience?: string;
  outcomes?: { label: string; value: string; source?: string }[];
  media?: string[];
  featured?: boolean;
  seo?: import("@/lib/content/types").SeoFields;
}

export const PROJECTS: Project[] = [
  {
    slug: "whx",
    title: "World Health Expo (WHX)",
    client: "American Hospital",
    event: "The World Health Expo",
    location: "Dubai, UAE",
    region: "uae",
    year: 2026,
    sector: "Healthcare",
    summary: "Motion-based displays that gave American Hospital a standout presence on a busy exhibition floor.",
    technologies: ["dna-xs", "arc-shift"],
    caseStudy: true,
  },
  {
    slug: "world-defense-show",
    title: "World Defense Show 2026",
    client: "SAMI",
    event: "World Defense Show 2026",
    location: "Riyadh, Saudi Arabia",
    region: "ksa",
    year: 2026,
    sector: "Defence & aviation",
    summary: "A custom TriAxis display with tailored content presenting complex systems clearly.",
    technologies: ["triaxis"],
  },
  {
    slug: "ifat",
    title: "IFAT",
    client: "MWAN",
    event: "IFAT 2026",
    location: "Riyadh, Saudi Arabia",
    region: "ksa",
    year: 2026,
    sector: "Government & sustainability",
    summary: "Sliding screen, presence-triggered content and a 30-inch OLED touch display.",
    technologies: ["sliding-screen"],
  },
  {
    slug: "world-future-energy-summit",
    title: "World Future Energy Summit",
    client: "UAE Ministry of Climate Change and Environment",
    event: "World Future Energy Summit",
    location: "Abu Dhabi, UAE",
    region: "uae",
    year: 2026,
    sector: "Government & sustainability",
    summary: "An immersive room turning climate and ecosystem themes into an intuitive journey.",
    technologies: ["immersive-room"],
  },
  {
    slug: "f1-etihad",
    title: "F1 Etihad Airways",
    client: "Etihad Airways",
    event: "F1 Etihad Airways Grand Prix",
    location: "Abu Dhabi, UAE",
    region: "uae",
    year: 2025,
    sector: "Sport & entertainment",
    summary: "A flight simulator, destination tunnel, three AI photobooths and a motion-activated penalty game.",
    technologies: ["ai-photobooth", "interactive-games"],
  },
  {
    slug: "games-of-the-future",
    title: "Games of the Future Roadshow",
    client: "",
    event: "Games of the Future Roadshow",
    location: "UAE (multi-location)",
    region: "uae",
    year: 2025,
    sector: "Sport & entertainment",
    summary: "A hybrid gaming roadshow blending physical sport with digital gameplay across several locations.",
    technologies: ["interactive-games", "ar-vr"],
  },
  {
    slug: "fifa-arab-cup",
    title: "FIFA Arab Cup Roadshow",
    client: "FIFA Arab Cup 2025",
    event: "FIFA Arab Cup 2025 Roadshow",
    location: "UAE, Qatar, Oman, Bahrain, KSA",
    region: "international",
    year: 2025,
    sector: "Sport & entertainment",
    summary: "A five-country fan experience with a VR penalty shootout and a branded AI photobooth.",
    technologies: ["ar-vr", "ai-photobooth"],
  },
  {
    slug: "cityscape",
    title: "Cityscape Riyadh",
    client: "IQ Real Estate and Hail Region Municipality",
    event: "Cityscape Riyadh",
    location: "Riyadh, Saudi Arabia",
    region: "ksa",
    year: 2025,
    sector: "Real estate & development",
    summary: "Kinetic systems, interactive media and bespoke stand environments for two exhibitors.",
    technologies: ["tri-helix", "arc-shift", "touch-and-throw", "robotic-arm"],
  },
  {
    slug: "dubai-air-show",
    title: "Dubai Airshow",
    client: "GAL, AMMROC and MRO",
    event: "Dubai Airshow",
    location: "Dubai, UAE",
    region: "uae",
    year: 2025,
    sector: "Defence & aviation",
    summary: "Spin-Slide displays, Tri-Helix kinetic structures and an interactive immersive room.",
    technologies: ["tri-helix", "immersive-room"],
  },
  {
    slug: "cop30",
    title: "COP30",
    client: "Global Biofuels Alliance",
    event: "COP30",
    location: "Belém, Brazil",
    region: "international",
    year: 2025,
    sector: "Government & sustainability",
    summary: "A circular screen, rotary touch interface and RFID interactions explaining biofuels hands-on.",
    technologies: ["touch-and-throw", "circular-dial"],
  },
  {
    slug: "chronicles-ahmed-al-maghribi",
    title: "The Chronicles of Ahmed Al Maghribi",
    client: "",
    event: "The Chronicles of Ahmed Al Maghribi",
    location: "Dubai, UAE",
    region: "uae",
    year: 2025,
    sector: "Culture & heritage",
    summary: "End-to-end conception, planning and delivery, with a robotic-arm screen and an immersive tunnel.",
    technologies: ["robotic-arm", "immersive-room"],
  },
  {
    slug: "global-health-exhibition",
    title: "Global Health Exhibition",
    client: "NUPCO, Sulaiman Al Habib, Mouwasat, Saudi Post, GO Telecom, Ejada, Saudi German Health, Dr. Samir and Baxter",
    event: "Global Health Exhibition",
    location: "Riyadh, Saudi Arabia",
    region: "ksa",
    year: 2025,
    sector: "Healthcare",
    summary: "Sixteen technology-led activations across nine booths.",
    technologies: ["tri-helix", "arc-revolve", "robotic-arm", "holofan", "sliding-screen"],
  },
  {
    slug: "gitex",
    title: "GITEX Global",
    client: "Cloudflare, AWS, Honeywell and Pure Storage",
    event: "GITEX Global",
    location: "Dubai, UAE",
    region: "uae",
    year: 2025,
    sector: "Technology & finance",
    summary: "An interactive globe, LED wall systems, sliding screens and an AI-driven immersive room.",
    technologies: ["sliding-screen", "immersive-room"],
  },
  {
    slug: "money-20-20",
    title: "Money 20/20",
    client: "ELM and Ejada",
    event: "Money 20/20",
    location: "Riyadh, Saudi Arabia",
    region: "ksa",
    year: 2025,
    sector: "Technology & finance",
    summary: "A digital content ecosystem for ELM and a kinetic wall and ceiling installation for Ejada.",
    technologies: ["kinetic-wall-ceiling"],
  },
  {
    slug: "atm",
    title: "Arabian Travel Market",
    client: "Riyadh Air and Visit Saudi",
    event: "Arabian Travel Market (ATM)",
    location: "Dubai, UAE",
    region: "uae",
    year: 2025,
    sector: "Travel & tourism",
    summary: "Motion content, a triangular-tile kinetic wall, a four-screen wall and a transparent OLED.",
    technologies: ["kinetic-wall-ceiling", "transparent-oled"],
  },
  {
    slug: "fahid-island",
    title: "Fahid Island",
    client: "Aldar",
    event: "Fahid Island",
    location: "Abu Dhabi, UAE",
    region: "uae",
    year: 2025,
    sector: "Real estate & development",
    summary: "Hardware and software for two sensory wellness technologies, ZenPod and PulseSense Station.",
    technologies: [],
  },
  {
    slug: "f1-jeddah",
    title: "F1 Jeddah",
    client: "stc",
    event: "F1 Jeddah",
    location: "Jeddah, Saudi Arabia",
    region: "ksa",
    year: 2025,
    sector: "Sport & entertainment",
    summary: "Mind-controlled slot car racing, a laser maze and a reflex drop challenge.",
    technologies: ["interactive-games"],
  },
  {
    slug: "umrah-ziyarah-forum",
    title: "Umrah & Ziyarah Forum",
    client: "",
    event: "Umrah & Ziyarah Forum",
    location: "Madinah, Saudi Arabia",
    region: "ksa",
    year: 2025,
    sector: "Culture & heritage",
    summary: "A Touch-and-Throw display with custom hardware, software and heritage content.",
    technologies: ["touch-and-throw"],
  },
  {
    slug: "aldar-wilds",
    title: "Aldar Wilds",
    client: "Aldar",
    event: "Aldar Wilds",
    location: "Dubai, UAE",
    region: "uae",
    year: 2025,
    sector: "Real estate & development",
    summary: "Creative content for an immersive nature tunnel and interactive touchpoint displays.",
    technologies: ["immersive-room"],
  },
  {
    slug: "invest-qatar",
    title: "Invest Qatar",
    client: "",
    event: "Web Summit Qatar",
    location: "Qatar",
    region: "international",
    year: 2025,
    sector: "Technology & finance",
    summary: "An AR tabletop and a voice-based AI assistant explaining the startup ecosystem.",
    technologies: ["ar-vr", "ai-assistant"],
  },
  {
    slug: "restatex",
    title: "Restatex",
    client: "",
    event: "Restatex",
    location: "Riyadh, Saudi Arabia",
    region: "ksa",
    year: 2025,
    sector: "Real estate & development",
    summary: "A kinetic screen centrepiece synchronised with purpose-built content.",
    technologies: [],
  },
  {
    slug: "idex",
    title: "IDEX",
    client: "CMN Naval",
    event: "IDEX",
    location: "Abu Dhabi, UAE",
    region: "uae",
    year: 2025,
    sector: "Defence & aviation",
    summary: "A circular dial interface driving 3D naval visuals on a synchronised main display.",
    technologies: ["circular-dial"],
  },
  {
    slug: "leap",
    title: "LEAP",
    client: "Tamkeen and Tawuniya",
    event: "LEAP 2025",
    location: "Riyadh, Saudi Arabia",
    region: "ksa",
    year: 2025,
    sector: "Technology & finance",
    summary: "Kinetic ceiling and walls, sliding screen, Tri-Helix and HoloFans moving in synchronised waves.",
    technologies: ["tri-helix", "kinetic-wall-ceiling", "sliding-screen", "holofan"],
  },
  {
    slug: "arab-health",
    title: "Arab Health",
    client: "GE Healthcare and PureHealth",
    event: "Arab Health",
    location: "WTC, Dubai, UAE",
    region: "uae",
    year: 2025,
    sector: "Healthcare",
    summary: "A transparent OLED, AI photobooth and fibre-optic lighting beneath a custom tree centrepiece.",
    technologies: ["transparent-oled", "ai-photobooth"],
  },
  {
    slug: "hajj-umrah-exhibition",
    title: "Hajj & Umrah Exhibition",
    client: "",
    event: "Hajj & Umrah Exhibition",
    location: "Riyadh, Saudi Arabia",
    region: "ksa",
    year: 2025,
    sector: "Culture & heritage",
    summary: "Gesture-based interactive graphic walls telling the Hajj journey in two languages.",
    technologies: ["interactive-wall"],
  },
  {
    slug: "iktva",
    title: "IKTVA",
    client: "Aramco",
    event: "IKTVA 2025",
    location: "Riyadh, Saudi Arabia",
    region: "ksa",
    year: 2025,
    sector: "Energy",
    summary: "Tri-Helix and a transparent touchscreen for exploring Aramco's ESG initiatives.",
    technologies: ["tri-helix", "transparent-oled"],
  },
];

export const projectBySlug = (slug: string) => PROJECTS.find((p) => p.slug === slug);
