// Generates src/content/map.ts: a static, projected map of Europe / Middle East / North Africa from real geographic
// data (Natural Earth via the `world-atlas` package). Run: npm i -D d3-geo topojson-client world-atlas && node scripts/build-map.mjs
import { readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { geoMercator, geoPath, geoGraticule } from "d3-geo";
import { feature, mesh } from "topojson-client";

const require = createRequire(import.meta.url);
const read = (n) => JSON.parse(readFileSync(require.resolve(`world-atlas/${n}`), "utf8"));
const land = read("land-50m.json");
const countries = read("countries-50m.json");

const W = 1000, H = 560;
const view = { type: "MultiPoint", coordinates: [[-12, 9], [70, 9], [70, 62], [-12, 62]] };
const projection = geoMercator().fitExtent([[0, 0], [W, H]], view).clipExtent([[0, 0], [W, H]]);
const path = geoPath(projection).digits(1);

const LOC = {
  dubai: [55.27, 25.2], riyadh: [46.68, 24.71], poland: [19.4, 52.1],
  jeddah: [39.17, 21.54], madinah: [39.61, 24.47], qatar: [51.2, 25.3], oman: [56.0, 20.6], bahrain: [50.55, 26.05],
};
const points = Object.fromEntries(Object.entries(LOC).map(([k, ll]) => { const [x, y] = projection(ll); return [k, { x: +x.toFixed(1), y: +y.toFixed(1) }]; }));

const landPath = path(feature(land, land.objects.land));
const borders = path(mesh(countries, countries.objects.countries, (a, b) => a !== b));
const grat = path(geoGraticule().step([10, 10])());

// Heavy geometry goes to a static, cacheable SVG (not into the page HTML or JS bundle).
const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${W} ${H}"><defs><pattern id="d" width="7" height="7" patternUnits="userSpaceOnUse"><circle cx="3.5" cy="3.5" r="1.25" fill="#27cdd8" fill-opacity=".34"/></pattern></defs><path d="${grat}" fill="none" stroke="#27cdd8" stroke-opacity=".1" stroke-width=".6"/><path d="${landPath}" fill="url(#d)" stroke="#27cdd8" stroke-opacity=".3" stroke-width=".6"/><path d="${borders}" fill="none" stroke="#27cdd8" stroke-opacity=".2" stroke-width=".5"/></svg>`;
writeFileSync(new URL("../public/art/map-land.svg", import.meta.url), svg);

const ts = `// GENERATED by scripts/build-map.mjs from Natural Earth (world-atlas). Do not edit by hand.\nexport const MAP = ${JSON.stringify({ width: W, height: H, points })} as const;\n`;
writeFileSync(new URL("../src/content/map.ts", import.meta.url), ts);
console.log("map-land.svg bytes:", svg.length, "| map.ts bytes:", ts.length);
console.log(points);
